# Generated by Django 5.1.7 on 2025-03-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_title',
            field=models.CharField(default='untitled', max_length=255),
        ),
    ]
