# Generated by Django 5.1.7 on 2025-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0006_projectsubmission_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='title',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('IT', 'Information Technology'), ('DB', 'Database'), ('js', 'javascript'), ('py', 'python')], default='AI', max_length=10),
        ),
    ]
