# Generated by Django 5.1.6 on 2025-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0007_remove_projectsubmission_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certificate_info',
            field=models.TextField(default='Certificate will be provided'),
        ),
        migrations.AlterField(
            model_name='course',
            name='project_info',
            field=models.TextField(default='Hands-on project at the end of the course'),
        ),
    ]
