# Generated by Django 5.1.6 on 2025-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0008_alter_course_certificate_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
