# Generated by Django 5.1.7 on 2025-04-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0013_alter_projectsubmission_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
    ]
