# Generated by Django 5.1.7 on 2025-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0014_userstats_is_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='links',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='BasicInfo',
        ),
    ]
