# Generated by Django 5.1.7 on 2025-05-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0019_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='content',
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecture',
            name='static_file_path',
            field=models.CharField(blank=True, help_text="Path to the static HTML file, e.g., 'AI_course/chapter1_lectures/lecture1_page1.html'", max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
