# Generated by Django 5.1.7 on 2025-05-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0020_remove_lecture_content_lecture_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True, help_text='Optional dynamic lecture content. Will be used if provided.', null=True),
        ),
    ]
