# Generated by Django 5.1.7 on 2025-05-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0022_remove_lecture_content_lecturecontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lecture',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='lecturecontent',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='static_file_path',
        ),
        migrations.RemoveField(
            model_name='lecturecontent',
            name='content',
        ),
        migrations.AddField(
            model_name='lecturecontent',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturecontent',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alignskills.chapter'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lecturecontent',
            name='content_type',
            field=models.CharField(choices=[('heading1', 'Main Heading (h1)'), ('heading2', 'Sub Heading (h2)'), ('heading3', 'Sub-sub Heading (h3)'), ('paragraph', 'Paragraph'), ('list', 'List'), ('image', 'Image')], max_length=20),
        ),
    ]
