# Generated by Django 5.1.7 on 2025-05-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0023_alter_lecture_options_alter_lecturecontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecontent',
            name='content_type',
            field=models.CharField(choices=[('heading1', 'Main Heading (h1)'), ('heading2', 'Sub Heading (h2)'), ('heading3', 'Sub-sub Heading (h3)'), ('paragraph', 'Paragraph'), ('list', 'List')], max_length=20),
        ),
    ]
