# Generated by Django 5.1.7 on 2025-05-02 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0024_alter_lecturecontent_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='alignskills.chapter'),
        ),
    ]
