# Generated by Django 5.1.7 on 2025-05-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0026_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alignskills.course'),
        ),
    ]
