# Generated by Django 5.1.7 on 2025-05-03 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0027_banner_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='alignskills.chapter')),
            ],
        ),
    ]
