# Generated by Django 5.1.7 on 2025-05-03 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0030_quiz_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='alignskills.chapter'),
        ),
    ]
