# Generated by Django 5.1.7 on 2025-05-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0033_alter_chapter_title_alter_quiz_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
