# Generated by Django 5.1.7 on 2025-05-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0035_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('example_links', models.TextField(blank=True, help_text='Enter links as HTML anchor tags')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='project',
            name='link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.ManyToManyField(blank=True, to='alignskills.projectrequirement'),
        ),
    ]
