# Generated by Django 5.1.7 on 2025-05-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0036_projectrequirement_remove_project_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='same as the course title', max_length=255),
        ),
    ]
