# Generated by Django 5.1.7 on 2025-05-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0037_project_project_name_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='course_title',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='alignskills.course'),
        ),
    ]
