# Generated by Django 5.1.7 on 2025-05-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0038_projectsubmission_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='course_title',
        ),
    ]
