# Generated by Django 5.1.7 on 2025-05-03 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0039_remove_projectsubmission_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='course_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alignskills.course'),
        ),
    ]
