# Generated by Django 5.1.7 on 2025-05-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0041_alter_projectsubmission_course_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='requirements',
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='alignskills.project'),
        ),
    ]
