# Generated by Django 5.1.7 on 2025-05-23 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alignskills', '0042_remove_project_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='alignskills.course'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='category',
            field=models.CharField(choices=[('AI', 'Artificial Intelligence'), ('IT', 'Information Technology'), ('DB', 'Database'), ('js', 'JavaScript'), ('py', 'Python'), ('ccn', 'Computer Network')], default='AI', max_length=10),
        ),
    ]
